name = "MaterialReconstruction"
uuid = "03cb9323-3c4b-4e23-a84c-921ade87b3a3"
authors = ["Vasily Postnicov <shamaz.mazum@gmail.com>"]
version = "0.2.4"

[deps]
AnnealingAPI = "ea73c536-af4e-4c29-9508-d79bc79c0161"
CorrelationFunctions = "cd8c4018-4f35-43b7-8520-d042ebaeaa2d"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
PoissonRandom = "e409e4f3-bfea-5376-8464-e040bb5c01ab"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
AnnealingAPI = "0.2, 0.3"
CorrelationFunctions = "0.7, 0.8"
CorrelationTrackers = "0.6"
LsqFit = "0.12, 0.13"
PoissonRandom = "0.4"
julia = "^1.0"

[extras]
CorrelationTrackers = "2aaf3720-2af0-4ca4-b7d9-7d970023fcad"
XUnit = "3e3c03f2-1a94-11e9-2981-050a4ca824ab"

[targets]
test = ["XUnit", "CorrelationTrackers"]
