name = "MaterialReconstruction"
uuid = "03cb9323-3c4b-4e23-a84c-921ade87b3a3"
authors = ["Vasily Postnicov <shamaz.mazum@gmail.com>"]
version = "0.1.0"

[deps]
CorrelationFunctions = "cd8c4018-4f35-43b7-8520-d042ebaeaa2d"
CorrelationTrackers = "2aaf3720-2af0-4ca4-b7d9-7d970023fcad"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CorrelationFunctions = "0.2.0"
CorrelationTrackers = "0.1.0"
julia = "^1.0"
